### ISSUE TITLE
'urlqoute' now deprecated in Django 4.0

### ISSUE THREAD

**Issue by hydromike** [inueni/django-subadmin#10]
ImportError: cannot import name 'urlquote' from 'django.utils.http'
This has been deprecated in Django 4.0,

**Comment by cyberbudy** [comment]
You can use my fork for now, it has a fix https://github.com/cyberbudy/django-subadmin.
I guess project is not maintained.

**Comment by sect2k** [comment]
Hey,

I just merged a patch from @cyberbudy and will make a new pypi release in a couple if days.

The project is not unmaintained, just we use in on some large deployments and it takes a while for them to upgrade the latest and gratest django release and it is otherwise feature complete, as far as our needs go.

**Comment by cyberbudy** [comment]
Great!

**Comment by jordanorc** [comment]
Hi @sect2k, any news about the package publication to pypi?

**Comment by denverprogrammer** [comment]
Hello,  I am also interested in when this release will be available on PyPi.

**Comment by juangonzaq** [comment]
¿Alguien sabe cuando aceptarán este cambio?

**Comment by sect2k** [comment]
Sorry it took so long, but life gets in the way sometimes.
